### ISSUE TITLE
Understanding how people use the web interface

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/playground#503]
There are tools like Hotjar that can create heatmaps of how people interact with the page. It would be nice to have this for Playground so we can optimize and improve the experience. This has a bunch of GDPR implications so we need to better understand the legal side of things. See https://www.hotjar.com/product/heatmaps/ for the product.

**Comment by SergioCasCeb** [comment]
To elaborate on the GDPR topic, Hotjar has taken significant steps to align with GDPR, and you can find detailed information about their commitment to GDPR compliance on their website at https://www.hotjar.com/legal/compliance/gdpr-commitment/.

On this page, Hotjar explicitly outlines the steps they've taken to adhere to GDPR legislation. However, as a customer, it is crucial to follow specific guidelines in order to implement Hotjar while maintaining GDPR compliance:

1. Transparent Communication: One key requirement is that the _Terms of Service_ or _Privacy Policy_ must effectively communicate to the users how you are using Hotjar, along with any other similar services, on your website or app. This means that you should clearly inform the users about data collection and its purpose.

3. Data Processing Agreement (DPA): If your operations fall under the European Union's jurisdiction, it is highly recommended to sign a Data Processing Agreement with Hotjar. This agreement, available at https://www.hotjar.com/legal/support/dpa/, offers a comprehensive understanding of various aspects of data processing. It covers topics such as the duration of data processing, the precise data being processed, procedures for data deletion, and the return of personal data.

It is essential to note that the specifics of data collection, processing duration, and more, are heavily dependent on how you configure the Hotjar service. You have significant control over these settings to align them with your GDPR compliance requirements. To illustrate this, please refer to the image below, where customers can suppress the collection of specific types of data such as location, email addresses, text, keystrokes, IP addresses, and more.

![image](https://github.com/eclipse-thingweb/playground/assets/72516762/6d6e4fff-6c83-463f-8dc2-6b960a5b13bb)

**Comment by egekorkan** [comment]
Opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3873

**Comment by egekorkan** [comment]
This service is not possible. We will get by with analytics. Closing as not planned
